server:
  port: 8080

spring:
  application:
    name: security-test-app
  
  # H2 Database 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Cache 설정
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

# Hexacore Security 설정
hexacore:
  security:
    enabled: true
    
    # JPA 영속성 활성화
    persistence:
      jpa:
        enabled: true
    
    # JWT 토큰 제공자 사용
    token-provider:
      provider: jwt
      jwt:
        enabled: true
        secret: mySecretKeyForTestingHexacoreSecurityLibrary123456789
        expiration: 3600000  # 1시간
        refresh-expiration: 86400000  # 24시간

# 보안 필터 활성화
security:
  auth:
    jwt:
      enabled: true

# Spring Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    build:
      enabled: true
    env:
      enabled: true

# 로깅 설정
logging:
  level:
    root: INFO
    com.dx.hexacore.security: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.securitytest: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"