security-starter:
  session:
    time-window-minutes: 15
    timeout-hours: 24
    max-failed-attempts: 5
  token:
    min-expires-in: 1
    max-expires-in: 86400
  validation:
    min-username-length: 3
    max-username-length: 50
    min-password-length: 8
    min-jwt-secret-length: 32
    recommended-jwt-secret-length: 64
  logging:
    suspicious-activity-threshold: 5
    suspicious-activity-time-window-minutes: 5
    max-log-message-length: 50
    top-stats-limit: 5

# 기본 Spring Boot 설정
spring:
  application:
    name: security-starter
    
  # JPA 설정 (테스트용)
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # H2 데이터베이스 설정 (테스트용)  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

# 로깅 설정
logging:
  level:
    com.dx.hexacore.security: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"